name: my-workflow
on: pull_request
jobs:
    build:
        runs-on: windows-2022
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup .NET 7.0
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 7.0.x
            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1.1
              with:
                vs-prerelease: true
            - name: Install MAUI Workloads
              run: |
                dotnet workload install maui --ignore-failed-sources
            - name: Restore Dependencies
              run: dotnet restore ControleFinanceiro.csproj

            - name: Build MAUI Windows
              run: msbuild ControleFinanceiro.csproj -r -p:Configuration=Release -p:RestorePackages=false -p:TargetFramework=net7.0-windows10.0.19041 /p:GenerateAppxPackageOnBuild=true



